server {
    listen 80;
    server_name senya-and-dasha.ru www.senya-and-dasha.ru;

    root /var/www/senya-and-dasha;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/html text/css application/javascript;
}
